import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

interface RussianException {
  /** A tracked file, or a directory prefix ending in "/". */
  readonly path: string;
  readonly reason: string;
}

/**
 * The only places where Russian is allowed. A whole file or a whole directory is excepted, never a line.
 * Everything else in the repository is English.
 */
const RUSSIAN_EXCEPTIONS: readonly RussianException[] = [
  {
    path: "src/i18n/ru.ts",
    reason: "The Russian dictionary of the interface.",
  },
  {
    path: "src/i18n/locales.ts",
    reason: "`ownName` is the name of the language in that language.",
  },
  {
    path: "docs/lighthouse/ru.report.html",
    reason: "A generated report of the Russian page.",
  },
  {
    path: "CLAUDE.md",
    reason: "Generated by `cyberzavod sync` from the harness.",
  },
  {
    path: ".claude/agents/",
    reason: "Agent roles generated by `cyberzavod sync` from the harness.",
  },
  {
    path: ".claude/skills/",
    reason: "Skills generated by `cyberzavod sync` from the harness.",
  },
  {
    path: ".claude/settings.json",
    reason:
      "The status message of the stop hook is written by `cyberzavod sync`.",
  },
  {
    path: ".cyberzavod/bin/cyberzavod.mjs",
    reason: "The harness executable, its texts are Russian.",
  },
];

const CYRILLIC_LETTER = /\p{Script=Cyrillic}/u;
const NUL_BYTE = 0;
const LINE_BREAK = /\r?\n/u;
const DIRECTORY_SUFFIX = "/";
const GIT_OUTPUT_LIMIT_BYTES = 64 * 1024 * 1024;

/** An exception is a file path, or a directory prefix ending in "/" that covers every file under it. */
function isCoveredBy(exceptedPath: string, path: string): boolean {
  return exceptedPath.endsWith(DIRECTORY_SUFFIX)
    ? path.startsWith(exceptedPath)
    : path === exceptedPath;
}

function isExcepted(path: string): boolean {
  return RUSSIAN_EXCEPTIONS.some(({ path: exceptedPath }) =>
    isCoveredBy(exceptedPath, path),
  );
}

/** Lines of a text with Cyrillic letters, as `<path>:<line>: <trimmed line>`. */
function findCyrillicLines(path: string, text: string): string[] {
  const findings: string[] = [];
  for (const [index, line] of text.split(LINE_BREAK).entries()) {
    if (CYRILLIC_LETTER.test(line)) {
      findings.push(`${path}:${String(index + 1)}: ${line.trim()}`);
    }
  }

  return findings;
}

const REPOSITORY_ROOT = fileURLToPath(new URL("../", import.meta.url));

function listTrackedFiles(): string[] {
  const output = execFileSync("git", ["ls-files", "-z"], {
    cwd: REPOSITORY_ROOT,
    encoding: "utf8",
    maxBuffer: GIT_OUTPUT_LIMIT_BYTES,
  });

  return output.split("\0").filter((path) => path !== "");
}

/** Tracked text files; a file with a NUL byte is binary (an image, say) and is skipped. */
function readTrackedTextFiles(): { path: string; text: string }[] {
  const files: { path: string; text: string }[] = [];
  for (const path of listTrackedFiles()) {
    const absolutePath = `${REPOSITORY_ROOT}${path}`;
    if (!existsSync(absolutePath)) continue;

    const content = readFileSync(absolutePath);
    if (content.includes(NUL_BYTE)) continue;

    files.push({ path, text: content.toString("utf8") });
  }

  return files;
}

// Written with escapes, so that this file itself has no Cyrillic (it is a Russian greeting).
const RUSSIAN_WORD = "\u041F\u0440\u0438\u0432\u0435\u0442";

describe("findCyrillicLines", () => {
  it("names the path and the line of every line with Cyrillic, trimmed", () => {
    const text = `first line\n  ${RUSSIAN_WORD} world  \nthird\n${RUSSIAN_WORD}`;

    expect(findCyrillicLines("docs/note.md", text)).toEqual([
      `docs/note.md:2: ${RUSSIAN_WORD} world`,
      `docs/note.md:4: ${RUSSIAN_WORD}`,
    ]);
  });

  it("counts lines the same way for Windows line breaks", () => {
    const text = `a\r\n${RUSSIAN_WORD}\r\nb`;

    expect(findCyrillicLines("a.txt", text)).toEqual([
      `a.txt:2: ${RUSSIAN_WORD}`,
    ]);
  });

  it.each([
    ["Latin", "Hello, Ann"],
    ["Greek", "Γεια σου"],
    ["CJK", "垃圾"],
    ["emoji", "\u{1F469}‍\u{1F469}‍\u{1F467}"],
    ["typography and currency", "1 250,50 ₽ — → … −"],
  ])("accepts %s", (_title, line) => {
    expect(findCyrillicLines("src/example.ts", line)).toEqual([]);
  });

  it("finds Cyrillic hidden inside a mixed line", () => {
    const line = `const label = "Add ${RUSSIAN_WORD}";`;

    expect(findCyrillicLines("src/example.ts", line)).toEqual([
      `src/example.ts:1: ${line}`,
    ]);
  });
});

describe("isExcepted", () => {
  it("covers an excepted file", () => {
    expect(isExcepted("src/i18n/ru.ts")).toBe(true);
  });

  it("covers every file under an excepted directory", () => {
    expect(isExcepted(".claude/agents/coder.md")).toBe(true);
  });

  it("does not extend an exception to a file with a similar path", () => {
    expect(isExcepted("src/i18n/ru.test.ts")).toBe(false);
    expect(isExcepted(".claude/agents-notes.md")).toBe(false);
  });
});

describe("RUSSIAN_EXCEPTIONS", () => {
  const trackedFiles = listTrackedFiles();

  it.each(RUSSIAN_EXCEPTIONS.map(({ path }) => path))(
    "%s names a tracked file or a directory with tracked files",
    (exceptedPath) => {
      const isTracked = trackedFiles.some((path) =>
        isCoveredBy(exceptedPath, path),
      );

      expect(isTracked).toBe(true);
    },
  );

  it("gives every exception a reason", () => {
    for (const { reason } of RUSSIAN_EXCEPTIONS) {
      expect(reason).not.toBe("");
    }
  });
});

describe("the repository", () => {
  it("has Cyrillic only in the excepted files", () => {
    const checkedFiles = readTrackedTextFiles().filter(
      ({ path }) => !isExcepted(path),
    );
    const findings = checkedFiles.flatMap(({ path, text }) =>
      findCyrillicLines(path, text),
    );

    expect(findings).toEqual([]);
  });
});
